# Form implementation generated from reading ui file 'Data/bot_widget.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playerColor = QtWidgets.QHBoxLayout()
        self.playerColor.setObjectName("playerColor")
        self.colorLabel = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorLabel.sizePolicy().hasHeightForWidth())
        self.colorLabel.setSizePolicy(sizePolicy)
        self.colorLabel.setObjectName("colorLabel")
        self.playerColor.addWidget(self.colorLabel)
        self.colorName = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorName.sizePolicy().hasHeightForWidth())
        self.colorName.setSizePolicy(sizePolicy)
        self.colorName.setObjectName("colorName")
        self.playerColor.addWidget(self.colorName)
        self.colorSwatch = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorSwatch.sizePolicy().hasHeightForWidth())
        self.colorSwatch.setSizePolicy(sizePolicy)
        self.colorSwatch.setMinimumSize(QtCore.QSize(16, 16))
        self.colorSwatch.setMaximumSize(QtCore.QSize(16, 16))
        self.colorSwatch.setAutoFillBackground(True)
        self.colorSwatch.setObjectName("colorSwatch")
        self.playerColor.addWidget(self.colorSwatch)
        self.verticalLayout.addLayout(self.playerColor)
        self.playerBot = QtWidgets.QComboBox(parent=Form)
        self.playerBot.setObjectName("playerBot")
        self.verticalLayout.addWidget(self.playerBot)
        self.playerBudget = QtWidgets.QHBoxLayout()
        self.playerBudget.setObjectName("playerBudget")
        self.budgetLabel = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.budgetLabel.sizePolicy().hasHeightForWidth())
        self.budgetLabel.setSizePolicy(sizePolicy)
        self.budgetLabel.setObjectName("budgetLabel")
        self.playerBudget.addWidget(self.budgetLabel)
        self.budgetValue = QtWidgets.QDoubleSpinBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.budgetValue.sizePolicy().hasHeightForWidth())
        self.budgetValue.setSizePolicy(sizePolicy)
        self.budgetValue.setProperty("value", 1.0)
        self.budgetValue.setObjectName("budgetValue")
        self.playerBudget.addWidget(self.budgetValue)
        self.verticalLayout.addLayout(self.playerBudget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Bot Widget"))
        self.colorLabel.setText(_translate("Form", "Color:"))
        self.colorName.setText(_translate("Form", "TextLabel"))
        self.budgetLabel.setText(_translate("Form", "Budget:"))
        self.budgetValue.setSuffix(_translate("Form", "s"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
